name: KJGTest
favicon: null
layout_spectrum: 0.2345298721920699
typography_spectrum: 0.7973413257859647
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7269802512601018
  lightness: 0.22711532469838858
  saturation: 0.21692054183222353
  rhythmicContrast: 0.8232143905479461
purpose: []
